/**
 * Database Migration: Add text_overlays column
 * Adds JSONB column for storing text overlay content generated by Layer 1
 */

import { Pool } from 'pg';
import dotenv from 'dotenv';

dotenv.config();

async function migrate() {
  const pool = new Pool({
    connectionString: process.env.DATABASE_URL,
  });

  console.log('Adding text_overlays column to content table...\n');

  try {
    // Check if column already exists
    const checkResult = await pool.query(`
      SELECT column_name
      FROM information_schema.columns
      WHERE table_name = 'content' AND column_name = 'text_overlays'
    `);

    if (checkResult.rows.length > 0) {
      console.log('Column text_overlays already exists. Skipping migration.');
      return;
    }

    // Add the column
    await pool.query(`
      ALTER TABLE content
      ADD COLUMN text_overlays JSONB
    `);

    console.log('Successfully added text_overlays column.\n');

    // Add comment for documentation
    await pool.query(`
      COMMENT ON COLUMN content.text_overlays IS 'JSON object containing introText, introSubtext (optional), and segmentLabels array for video text overlays'
    `);

    console.log('Migration completed successfully!');
  } catch (error) {
    console.error('Migration failed:', error);
    throw error;
  } finally {
    await pool.end();
  }
}

migrate().catch((err) => {
  console.error(err);
  process.exit(1);
});
